/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  rules: {
    "declaration-block-no-duplicate-properties": true,
    "font-family-no-duplicate-names": true,
    "keyframe-block-no-duplicate-selectors": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "block-no-empty": true,
    "comment-no-empty": true,
    "color-no-invalid-hex": true,
    "no-invalid-double-slash-comments": true,
    "no-invalid-position-at-import-rule": true,
    "no-invalid-position-declaration": true,
    "syntax-string-no-invalid": true,
    "selector-anb-no-unmatchable": true,
    "function-no-unknown": true,
    "declaration-property-value-no-unknown": true,
    "at-rule-no-unknown": true,
    "no-unknown-animations": true,
    "no-unknown-custom-properties": true,
    "property-no-unknown": true,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": true,
    "unit-no-unknown": true,
  },
}
